export { analyzeSvg } from './analyze'
export type { SvgAnalysis } from './analyze'
export { extractGeometry } from './geometry'
export type { SvgElementKind, SvgGeometry, SvgGeometryShape } from './geometry'
export { buildPathData, formatNumber } from './pathdata'
export { optimizePathData } from './optimize'
export { cleanCommands } from './clean'
export { arcToCubics, fitArcs } from './arc'
export { detectPrimitive } from './primitive'
export type { Primitive } from './primitive'
export { serializeSvg, shapeOut } from './serialize'
export type { SerializeOptions, ShapeOut, SvgDocument, SvgGradient, SvgShape } from './serialize'
